/**
 * Static demo data for full-app seed (Inova Ride — Tunisia fleet).
 * Images: Unsplash stock photos matched to each body type / segment.
 */

import type { VehicleCategory, FuelType, TransmissionType } from '../types/models';

const img = (id: string, w = 1200) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&q=85&auto=format&fit=crop`;

export const DEFAULT_AGENCY = {
  name: 'Inova Ride Tunisie',
  slug: 'inova-ride',
  address: 'Avenue Habib Bourguiba, Tunis 1000, Tunisie',
  phone: '+216 71 000 000',
};

export interface SeedVehicleDef {
  brand: string;
  model: string;
  year: number;
  licensePlate: string;
  category: VehicleCategory;
  color: string;
  seats: number;
  transmission: TransmissionType;
  fuelType: FuelType;
  pricePerDay: number;
  images: string[];
  description: string;
  features: string[];
  mileage: number;
  isAvailable: boolean;
  maintenanceDueDays?: number;
}

export const SEED_VEHICLES: SeedVehicleDef[] = [
  {
    brand: 'Volkswagen',
    model: 'Polo',
    year: 2023,
    licensePlate: 'TU-1024-A',
    category: 'economy',
    color: 'Blanc Candy',
    seats: 5,
    transmission: 'manual',
    fuelType: 'petrol',
    pricePerDay: 75,
    images: [img('1494977668657-f9d793c623d4'), img('1549317661-32f03c8f5640')],
    description: 'Citadine Volkswagen fiable, idéale pour la ville et les déplacements quotidiens à Tunis.',
    features: ['Climatisation', 'Bluetooth', 'Radar arrière', 'Start & Stop'],
    mileage: 28400,
    isAvailable: true,
  },
  {
    brand: 'Volkswagen',
    model: 'Golf',
    year: 2022,
    licensePlate: 'TU-2048-B',
    category: 'economy',
    color: 'Gris Indium',
    seats: 5,
    transmission: 'automatic',
    fuelType: 'petrol',
    pricePerDay: 95,
    images: [img('1549399542-7e3f8b79c341'), img('1606664515524-b4bbb9682918')],
    description: 'Compacte premium VW Golf — confort, sécurité et consommation maîtrisée.',
    features: ['GPS', 'Caméra recul', 'Apple CarPlay', 'Régulateur adaptatif'],
    mileage: 41200,
    isAvailable: true,
  },
  {
    brand: 'Volkswagen',
    model: 'Passat',
    year: 2021,
    licensePlate: 'TU-3072-C',
    category: 'luxury',
    color: 'Noir Deep',
    seats: 5,
    transmission: 'automatic',
    fuelType: 'diesel',
    pricePerDay: 145,
    images: [img('1606664515524-9846f038747b'), img('1519641471654-76cefc7a8ad6')],
    description: 'Berline routière haut de gamme pour voyages d\'affaires et longues distances.',
    features: ['Cuir', 'Toit ouvrant', 'Sièges chauffants', 'ACC'],
    mileage: 67800,
    isAvailable: true,
  },
  {
    brand: 'Volkswagen',
    model: 'Tiguan',
    year: 2023,
    licensePlate: 'TU-4096-D',
    category: 'suv',
    color: 'Bleu Atlantic',
    seats: 5,
    transmission: 'automatic',
    fuelType: 'diesel',
    pricePerDay: 165,
    images: [img('1519641471654-76cefc7a8ad6'), img('1544636331-e26879cd4d9b')],
    description: 'SUV familial spacieux, parfait pour la côte et les routes du Sahel.',
    features: ['4MOTION', 'Hayon électrique', '360° caméra', '7 places option'],
    mileage: 22100,
    isAvailable: false,
    maintenanceDueDays: 5,
  },
  {
    brand: 'Skoda',
    model: 'Fabia',
    year: 2024,
    licensePlate: 'TU-5120-E',
    category: 'economy',
    color: 'Rouge Corrida',
    seats: 5,
    transmission: 'manual',
    fuelType: 'petrol',
    pricePerDay: 65,
    images: [img('1609521263047-f8f205293f24'), img('1549317661-32f03c8f5640')],
    description: 'Skoda Fabia — économique, agile et très demandée en location courte durée.',
    features: ['Climatisation', 'USB-C', 'ESP', 'Limiteur'],
    mileage: 8900,
    isAvailable: true,
  },
  {
    brand: 'Skoda',
    model: 'Octavia',
    year: 2022,
    licensePlate: 'TU-6144-F',
    category: 'economy',
    color: 'Gris Quartz',
    seats: 5,
    transmission: 'automatic',
    fuelType: 'diesel',
    pricePerDay: 110,
    images: [img('1606664515524-b4bbb9682918'), img('1552513507-a06aa7527621')],
    description: 'Break compact Skoda Octavia — grand coffre, idéal pour familles et pros.',
    features: ['GPS', 'Régulateur', 'Bluetooth', 'Phares LED'],
    mileage: 53400,
    isAvailable: true,
  },
  {
    brand: 'Skoda',
    model: 'Superb',
    year: 2021,
    licensePlate: 'TU-7168-G',
    category: 'luxury',
    color: 'Blanc Luna',
    seats: 5,
    transmission: 'automatic',
    fuelType: 'diesel',
    pricePerDay: 175,
    images: [img('1618843479313-40f8afb4b4d8'), img('1618843479354-42d249164da5')],
    description: 'Berline exécutive Skoda Superb — silence de roulement et finitions premium.',
    features: ['Cuir Alcantara', 'Massage', 'Head-up display', 'ACC'],
    mileage: 72100,
    isAvailable: true,
  },
  {
    brand: 'Seat',
    model: 'Ibiza',
    year: 2023,
    licensePlate: 'TU-8192-H',
    category: 'economy',
    color: 'Orange Desire',
    seats: 5,
    transmission: 'manual',
    fuelType: 'petrol',
    pricePerDay: 70,
    images: [img('1549317661-32f03c8f5640'), img('1494977668657-f9d793c623d4')],
    description: 'Seat Ibiza sportive et économique — parfaite pour jeunes conducteurs.',
    features: ['Climatisation auto', 'Full Link', 'Feux LED', 'Mode Sport'],
    mileage: 15600,
    isAvailable: true,
  },
  {
    brand: 'Seat',
    model: 'Leon',
    year: 2022,
    licensePlate: 'TU-9216-J',
    category: 'economy',
    color: 'Gris Magnetic',
    seats: 5,
    transmission: 'automatic',
    fuelType: 'petrol',
    pricePerDay: 105,
    images: [img('1552513507-a06aa7527621'), img('1606664515524-9846f038747b')],
    description: 'Seat Leon FR — dynamique, connectée et confortable pour tout type de trajet.',
    features: ['Digital Cockpit', 'ACC', 'Sièges sport', 'Park Assist'],
    mileage: 38900,
    isAvailable: true,
  },
  {
    brand: 'Seat',
    model: 'Ateca',
    year: 2023,
    licensePlate: 'TU-10240-K',
    category: 'suv',
    color: 'Vert Dark',
    seats: 5,
    transmission: 'automatic',
    fuelType: 'diesel',
    pricePerDay: 155,
    images: [img('1544636331-e26879cd4d9b'), img('1519641471654-76cefc7a8ad6')],
    description: 'SUV Seat Ateca — polyvalent pour ville, autoroute et chemins du Cap Bon.',
    features: ['4Drive', 'Toit panoramique', 'Caméra 360°', 'GPS'],
    mileage: 19800,
    isAvailable: true,
  },
  {
    brand: 'Hyundai',
    model: 'i20',
    year: 2024,
    licensePlate: 'TU-11264-L',
    category: 'economy',
    color: 'Bleu Intense',
    seats: 5,
    transmission: 'manual',
    fuelType: 'petrol',
    pricePerDay: 68,
    images: [img('1619682817484-e59404655131'), img('1609521263047-f8f205293f24')],
    description: 'Hyundai i20 récente — garantie constructeur, faible consommation, très populaire.',
    features: ['Climatisation', 'Bluetooth', 'Caméra recul', 'Garantie 5 ans'],
    mileage: 6200,
    isAvailable: true,
  },
  {
    brand: 'Toyota',
    model: 'Hilux Double Cab',
    year: 2022,
    licensePlate: 'TU-12288-M',
    category: 'utility',
    color: 'Blanc Glacier',
    seats: 5,
    transmission: 'manual',
    fuelType: 'diesel',
    pricePerDay: 185,
    images: [img('1533474716605-e19255ec8865'), img('1590369286289-7c8aef204653')],
    description: 'Pick-up Toyota Hilux légendaire — chantier, agriculture, tout-terrain côtier.',
    features: ['4x4', 'Benne renforcée', 'Barres de toit', 'Climatisation bi-zone'],
    mileage: 84700,
    isAvailable: true,
  },
  {
    brand: 'Mercedes-Benz',
    model: 'Sprinter L3H2',
    year: 2021,
    licensePlate: 'TU-13312-N',
    category: 'van',
    color: 'Blanc Arctique',
    seats: 3,
    transmission: 'manual',
    fuelType: 'diesel',
    pricePerDay: 220,
    images: [img('1568605117034-5fe5e7bab0b7'), img('1623869675781-a571183f1fa7')],
    description: 'Fourgon Mercedes Sprinter — déménagement, livraison, équipes BTP.',
    features: ['Hayon élévateur', '14 m³ volume', 'GPS pro', 'Cruise control'],
    mileage: 112000,
    isAvailable: true,
  },
  {
    brand: 'Ford',
    model: 'Transit Custom',
    year: 2022,
    licensePlate: 'TU-14336-P',
    category: 'van',
    color: 'Gris Magnetic',
    seats: 3,
    transmission: 'manual',
    fuelType: 'diesel',
    pricePerDay: 195,
    images: [img('1559416523-140ddc3d275c'), img('1568605117034-5fe5e7bab0b7')],
    description: 'Ford Transit Custom — utilitaire polyvalent pour artisans et PME.',
    features: ['Porte latérale', '6.0 m³', 'Bluetooth', 'Régulateur'],
    mileage: 76500,
    isAvailable: true,
  },
  {
    brand: 'Renault',
    model: 'Master L2H2',
    year: 2020,
    licensePlate: 'TU-15360-R',
    category: 'van',
    color: 'Blanc',
    seats: 3,
    transmission: 'manual',
    fuelType: 'diesel',
    pricePerDay: 175,
    images: [img('1623869675781-a571183f1fa7'), img('1559416523-140ddc3d275c')],
    description: 'Renault Master — grand volume utile, location longue durée entreprises.',
    features: ['12 m³', 'Hayon', 'Climatisation', 'Caméra recul'],
    mileage: 134500,
    isAvailable: false,
  },
  {
    brand: 'Peugeot',
    model: 'Boxer L3H2',
    year: 2021,
    licensePlate: 'TU-16384-S',
    category: 'utility',
    color: 'Blanc Banquise',
    seats: 3,
    transmission: 'manual',
    fuelType: 'diesel',
    pricePerDay: 185,
    images: [img('1623869675781-a571183f1fa7'), img('1568605117034-5fe5e7bab0b7')],
    description: 'Peugeot Boxer utilitaire — transport marchandises et équipements lourds.',
    features: ['13 m³', 'Ramp access', 'GPS', 'ABS + ESP'],
    mileage: 98700,
    isAvailable: true,
  },
];

export interface SeedStaffDef {
  name: string;
  email: string;
  password: string;
  role: 'admin' | 'employee';
}

export const SEED_STAFF: SeedStaffDef[] = [
  {
    name: 'Karim Ben Salah',
    email: 'admin@inovaride.com',
    password: 'Admin123!',
    role: 'admin',
  },
  {
    name: 'Amira Trabelsi',
    email: 'agent@inovaride.com',
    password: 'Agent123!',
    role: 'employee',
  },
  {
    name: 'Youssef Mabrouk',
    email: 'youssef@inovaride.com',
    password: 'Agent123!',
    role: 'employee',
  },
];

export interface SeedClientDef {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  phone: string;
  nationality: string;
  idType: 'cin' | 'passport' | 'driving_license';
  idNumber: string;
  address: string;
  dateOfBirth: Date;
  totalRentals: number;
  lastLoginDaysAgo?: number;
}

export const SEED_CLIENTS: SeedClientDef[] = [
  {
    firstName: 'Mohamed',
    lastName: 'Gharbi',
    email: 'mohamed.gharbi@gmail.com',
    password: 'Client123!',
    phone: '+216 98 111 222',
    nationality: 'Tunisienne',
    idType: 'cin',
    idNumber: '12345678',
    address: 'La Marsa, Tunis',
    dateOfBirth: new Date('1988-03-15'),
    totalRentals: 12,
    lastLoginDaysAgo: 2,
  },
  {
    firstName: 'Salma',
    lastName: 'Ayari',
    email: 'salma.ayari@outlook.com',
    password: 'Client123!',
    phone: '+216 22 333 444',
    nationality: 'Tunisienne',
    idType: 'cin',
    idNumber: '87654321',
    address: 'Sousse, Centre-ville',
    dateOfBirth: new Date('1995-07-22'),
    totalRentals: 8,
    lastLoginDaysAgo: 5,
  },
  {
    firstName: 'Lucas',
    lastName: 'Martin',
    email: 'lucas.martin@email.fr',
    password: 'Client123!',
    phone: '+33 6 12 34 56 78',
    nationality: 'Française',
    idType: 'passport',
    idNumber: '18AF12345',
    address: 'Hôtel Mövenpick, Sousse',
    dateOfBirth: new Date('1990-11-08'),
    totalRentals: 3,
    lastLoginDaysAgo: 14,
  },
  {
    firstName: 'Fatma',
    lastName: 'Jebali',
    email: 'fatma.jebali@yahoo.com',
    password: 'Client123!',
    phone: '+216 55 666 777',
    nationality: 'Tunisienne',
    idType: 'cin',
    idNumber: '11223344',
    address: 'Monastir, Route de l\'Aéroport',
    dateOfBirth: new Date('1982-01-30'),
    totalRentals: 21,
    lastLoginDaysAgo: 1,
  },
  {
    firstName: 'Ahmed',
    lastName: 'Bouazizi',
    email: 'ahmed.bouazizi@pro.tn',
    password: 'Client123!',
    phone: '+216 70 888 999',
    nationality: 'Tunisienne',
    idType: 'cin',
    idNumber: '55667788',
    address: 'Sfax, Zone Industrielle',
    dateOfBirth: new Date('1979-09-12'),
    totalRentals: 34,
    lastLoginDaysAgo: 3,
  },
  {
    firstName: 'Nadia',
    lastName: 'Khelifi',
    email: 'nadia.khelifi@gmail.com',
    password: 'Client123!',
    phone: '+216 21 000 111',
    nationality: 'Tunisienne',
    idType: 'cin',
    idNumber: '99887766',
    address: 'Hammamet, Yasmine',
    dateOfBirth: new Date('1993-04-18'),
    totalRentals: 6,
    lastLoginDaysAgo: 30,
  },
  {
    firstName: 'Thomas',
    lastName: 'Weber',
    email: 't.weber@company.de',
    password: 'Client123!',
    phone: '+49 170 1234567',
    nationality: 'Allemande',
    idType: 'passport',
    idNumber: 'C01X2345Z',
    address: 'Tunis, Lac 2',
    dateOfBirth: new Date('1985-12-05'),
    totalRentals: 4,
    lastLoginDaysAgo: 45,
  },
  {
    firstName: 'Rim',
    lastName: 'Chaabane',
    email: 'rim.chaabane@live.com',
    password: 'Client123!',
    phone: '+216 98 222 333',
    nationality: 'Tunisienne',
    idType: 'cin',
    idNumber: '44332211',
    address: 'Bizerte, Corniche',
    dateOfBirth: new Date('1998-06-25'),
    totalRentals: 2,
    lastLoginDaysAgo: 7,
  },
  {
    firstName: 'Hedi',
    lastName: 'Sassi',
    email: 'hedi.sassi@entreprise.tn',
    password: 'Client123!',
    phone: '+216 71 444 555',
    nationality: 'Tunisienne',
    idType: 'cin',
    idNumber: '66778899',
    address: 'Tunis, Berges du Lac',
    dateOfBirth: new Date('1975-02-14'),
    totalRentals: 47,
    lastLoginDaysAgo: 0,
  },
  {
    firstName: 'Ines',
    lastName: 'Mansouri',
    email: 'ines.mansouri@gmail.com',
    password: 'Client123!',
    phone: '+216 56 777 888',
    nationality: 'Tunisienne',
    idType: 'cin',
    idNumber: '22114433',
    address: 'Nabeul, Kélibia',
    dateOfBirth: new Date('1991-08-09'),
    totalRentals: 9,
    lastLoginDaysAgo: 12,
  },
];

export const PICKUP_LOCATIONS = [
  'Aéroport Tunis-Carthage — Terminal 1',
  'Agence Inova Ride — Avenue Habib Bourguiba, Tunis',
  'Gare de Sousse — Centre-ville',
  'Aéroport Monastir Habib Bourguiba',
  'Hammamet — Zone touristique',
  'Sfax — Route de l\'Aéroport',
] as const;
